on:
  workflow_dispatch:
  release:
    types:
      - created

name: Release

jobs:
  sdist:
    name: Creating source release

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Installing dev dependencies
      run: |
          poetry install --with dev

    - name: Publishing
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: |
        poetry config pypi-token.pypi $PYPI_TOKEN
        poetry publish --build
        
    - name: Building documentation
      run: |
        cd docs && poetry run sphinx-build -b html source build

    - name: Publishing documentation
      run: |
        poetry run ghp-import -f -n -p docs/build
